### PR TITLE
Android audio Format

### PR DESCRIPTION
**Pull request by SamSam9812**
Just updated about android audio file format, but I haven't tested it yet

### CODE REVIEW

**Comment by SamSam9812** [comment]
I just fixed the bug , and I found a new issue with is the uploadMedia - Error: [TypeError: Network request failed],When I finished recording, there was a problem uploading audio on Android。

**Comment by SamSam9812** [comment]
The bug has been fixed and a test case has been created. Now the Android client can record successfully, but there is a problem with uploading the recording.

**Review by yashb196 — COMMENTED** [review]
as the changes require more work I am not pushing this to the main we will fix these bugs together

**Comment by yashb196** [comment]
Since this bug may require additional help for the next week tasks i am adding @irvinet20 to help you for the android bugs

**Review by yashb196 — APPROVED** [review]
looks good we will add the conversion of ios as a new issue pushing the branch to main

**Pull request merged**
